services:
  mem0_store:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/mem0/storage
  openmemory-mcp:
    build: 
      context: ..
      dockerfile: openmemory/api/Dockerfile
    environment:
      - OPENAI_API_KEY=
      - MISTRAL_API_KEY=IbbWhBGpLxlDoSrZ1caQqKQG6YGaBUSN
      - USER=moot
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
      - PROVIDER=mistral
      - AUTO_CONFIGURE=true
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"

volumes:
  mem0_storage:
